on:
  push: { }
  pull_request:
    branches-ignore:
      - renovate/**
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: "bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}"
          restore-keys: |
            bun-${{ runner.os }}-
      - name: Cache Playwright
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: "playwright-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}"
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check
        continue-on-error: true
        run: bun run check
      - name: Lint
        continue-on-error: true
        run: bun run lint
      - name: Build
        run: bun run build
      - name: Unit Tests
        run: bun run test:unit --run
      - name: Install Playwright
        run: bun run playwright install --with-deps
      - name: E2E Tests
        run: bun run test:e2e
