on:
  push: { }
  pull_request:
    branches-ignore:
      - renovate/**
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check
        continue-on-error: true
        run: yarn run check
      - name: Lint
        continue-on-error: true
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Unit Tests
        run: yarn run test:unit --run
      - name: Install Playwright
        run: yarn playwright install --with-deps
      - name: E2E Tests
        run: yarn run test:e2e
