on:
  push: {}
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 'latest'
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Pnpm Cache
        with:
          path: '${{ env.STORE_PATH }}'
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Playwright Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: "${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm run check
        continue-on-error: true
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
      - name: Unit Tests
        run: pnpm run test:unit --run
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: E2E Tests
        run: pnpm run test:e2e
